name: Continuous Deployment - Release

on:
  push:
    tags:
      - 'R.20*' # tags starting from R.20

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    concurrency:
      group: release
    runs-on: ubuntu-latest

    steps:
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ziemowits/hello
#          flavor: |
#            latest=false
#            prefix=
#            suffix=
#          tags: |
#            type=ref,event=tag
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Setup Maven Action
#        uses: s4u/setup-maven-action@v1.7.0
#        with:
#          java-version: '21'
#          java-distribution: 'temurin'
#
#      - name: Build
#        run: ./mvnw clean package -DskipTests=true
#
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          labels: ${{ steps.meta.outputs.labels }}
#          tags: ${{ steps.meta.outputs.tags }}

      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ziemowit/infra

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          format: 'YAML'
          valueFile: 'k8s/prod/hello-deployment.yaml'
          propertyPath: 'spec.kind.spec.containers[0].image'
          value: 'kopytko'
          targetBranch: master
          createPR: true
          message: 'Update Image Version to ${{ steps.meta.outputs.tags }}'
